application: powerful-atlas-707

version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bground.jpg
  static_files: bground.jpg
  upload: bground.jpg

- url: /TrinHackStyle.css
  static_files: TrinHackStyle.css
  upload: TrinHackStyle.css

- url: /TrinHackRepStyle.css
  static_files: TrinHackRepStyle.css
  upload: TrinHackRepStyle.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
